name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Welcome to the project, Contributor! 🎉 Thank you for opening an issue. Your contribution is appreciated! 🙌 Please make sure to follow our contribution guidelines and feel free to ask any questions if needed."
        pr-message: "👋 Welcome to the project, Contributor! 🎉 Thank you for opening a pull request. Your contribution is appreciated! 🙌 Please make sure to follow our contribution guidelines and feel free to ask any questions if needed."
